services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 1234:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: oFFuhWjUwrpTEoQm
volumes:
  db_data:
